"""Build Procedures and Acquisition objects from a per-subject config.

Public entry points:
    build_procedures(subject_id, cfg) -> Procedures
    build_mapseq_acquisition(subject_id, cfg, procedures) -> Acquisition
    build_barseq_acquisition(subject_id, cfg, procedures) -> Acquisition

The acquisition specimen_id lists are *derived from the procedures object*
to guarantee the two stay in sync:
    * MAPseq acquisition uses the chunk-level outputs (e.g. 780345_map001_001)
      from the Sectioning sub-procedures (the brain-region pieces sent to CSHL).
    * BARseq acquisition uses the section-level outputs (e.g. 780345_bar001)
      from the BARseq LC PlanarSectioning (the slides imaged in-house).
"""

import re
from datetime import date
from typing import List, Optional

from aind_data_schema_models.brain_atlas import CCFv3
from aind_data_schema_models.modalities import Modality
from aind_data_schema_models.units import SizeUnit

from aind_data_schema.components.coordinates import AtlasLibrary
from aind_data_schema.components.specimen_procedures import (
    PlanarSectioning,
    Section,
    Sectioning,
    SpecimenProcedure,
)
from aind_data_schema.core.acquisition import Acquisition, ExternalDataStream
from aind_data_schema.core.procedures import Procedures

from _procedures_helpers import (
    create_nonuniform_sections,
    create_planar_sectioning,
    create_uniform_sections,
    generate_mapseq_slide_chunks,
)

# ---------------------------------------------------------------------------
# Sectioning constants (shared across subjects, sourced from PR #1763)
# ---------------------------------------------------------------------------
_MAPSEQ_FIRST_BATCH_SPAN_UM = 9800       # spread across plates 0-98
_MAPSEQ_SECOND_BATCH_ORIGIN_UM = 11200   # plates 112+
_MAPSEQ_SECOND_BATCH_SPAN_UM = 2000      # spread across plates 112-132
_MAPSEQ_THICKNESS_UM = 300               # partial slices for both batches
_BARSEQ_START_UM = 9900                  # LC range begins here
_BARSEQ_THICKNESS_UM = 20                # uniform spacing
_SPINAL_THICKNESS_UM = 1000              # approximate

# TODO: confirm actual sectioning dates with Polina Kosillo. Placeholder
# matches PR #1763. Sectioning happened in-house at the Allen Institute
# before tissue was shipped to CSHL.
_SECTIONING_DATE = date(2024, 1, 1)
_SECTIONING_EXPERIMENTERS = ["Polina Kosillo"]

# ---------------------------------------------------------------------------
# Acquisition constants
# ---------------------------------------------------------------------------
_BARSEQ_PROTOCOL_ID = ["https://www.protocols.io/view/barseq-2-5-kqdg3ke9qv25/v1"]
_MAPSEQ_PROTOCOL_ID: List[str] = []  # No published MAPseq protocol URL.

_MAPSEQ_ACQUISITION_NOTE = (
    "MAPseq was performed off-site at Cold Spring Harbor Laboratory. "
    "The acquisition_start_time represents the date the tissue was mailed to "
    "CSHL; the acquisition_end_time represents the date the final processed "
    "results were received."
)
_MAPSEQ_STREAM_NOTE = "Acquired off-site at Cold Spring Harbor Laboratory."

_BARSEQ_ACQUISITION_NOTE = (
    "BARseq acquisition performed across multiple slides imaged over multiple days. "
    "Full acquisition includes gene sequencing (7 cycles), barcode sequencing (15 cycles), "
    "and one hybridization cycle. Each slide folder contains all three acquisition types. "
    "Final processed output is a cell x gene x barcode table registered to Allen CCFv3."
)
_BARSEQ_STREAM_NOTE = "Acquired by the Allen Institute for Brain Science BARseq imaging team."

# ---------------------------------------------------------------------------
# Provenance
# ---------------------------------------------------------------------------
# Once this capsule is published as a Code Ocean release, set this to the
# release URL. It will be appended to the `notes` field of every generated
# JSON so a downstream reader can trace each artifact back to the exact
# code that produced it.
PROVENANCE_URL: Optional[str] = None  # e.g. "https://codeocean.allenneuraldynamics.org/capsule/<id>"

# ---------------------------------------------------------------------------
# Specimen-id pattern filters
# ---------------------------------------------------------------------------
_CHUNK_PATTERN = re.compile(r"_map\d{3}_\d{3}$")  # e.g. 780345_map001_001
_BAR_PATTERN = re.compile(r"_bar\d{3}$")          # e.g. 780345_bar001


def _augment_notes(notes: str) -> str:
    """Append the provenance URL to a notes string if PROVENANCE_URL is set."""
    if PROVENANCE_URL:
        return f"{notes}\n\nGenerated by: {PROVENANCE_URL}"
    return notes


# ---------------------------------------------------------------------------
# Sectioning sub-procedure builders
# ---------------------------------------------------------------------------
def _mapseq_first_batch(subject_id: str, cfg: dict) -> PlanarSectioning:
    n = cfg["mapseq_first_batch_count"]
    starts = [i * (_MAPSEQ_FIRST_BATCH_SPAN_UM / n) for i in range(n)]
    sections = create_nonuniform_sections(
        specimen_id=subject_id,
        num_sections=n,
        start_positions_um=starts,
        thickness=_MAPSEQ_THICKNESS_UM,
        thickness_unit=SizeUnit.UM,
        section_prefix="map",
        start_section_num=1,
    )
    return create_planar_sectioning(sections)


def _mapseq_second_batch(subject_id: str, cfg: dict) -> PlanarSectioning:
    n = cfg["mapseq_second_batch_count"]
    start = cfg["mapseq_first_batch_count"] + 1
    starts = [
        _MAPSEQ_SECOND_BATCH_ORIGIN_UM + i * (_MAPSEQ_SECOND_BATCH_SPAN_UM / n)
        for i in range(n)
    ]
    sections = create_nonuniform_sections(
        specimen_id=subject_id,
        num_sections=n,
        start_positions_um=starts,
        thickness=_MAPSEQ_THICKNESS_UM,
        thickness_unit=SizeUnit.UM,
        section_prefix="map",
        start_section_num=start,
    )
    return create_planar_sectioning(sections)


def _barseq_lc(subject_id: str, cfg: dict) -> PlanarSectioning:
    sections = create_uniform_sections(
        specimen_id=subject_id,
        start_section_num=1,
        num_sections=cfg["barseq_count"],
        start_um=_BARSEQ_START_UM,
        thickness=_BARSEQ_THICKNESS_UM,
        thickness_unit=SizeUnit.UM,
        section_prefix="bar",
    )
    return create_planar_sectioning(sections)


def _spinal(subject_id: str, cfg: dict) -> Sectioning:
    return Sectioning(
        sections=[
            Section(
                output_specimen_id=f"{subject_id}_spinal",
                targeted_structure=CCFv3.CST,
                thickness=_SPINAL_THICKNESS_UM,
                thickness_unit=SizeUnit.UM,
            )
            for _ in range(cfg["spinal_section_count"])
        ]
    )


# ---------------------------------------------------------------------------
# Public builders
# ---------------------------------------------------------------------------
def build_procedures(subject_id: str, cfg: dict) -> Procedures:
    n_first = cfg["mapseq_first_batch_count"]
    n_second = cfg["mapseq_second_batch_count"]
    return Procedures(
        subject_id=subject_id,
        coordinate_system=AtlasLibrary.CCFv3_10um,
        specimen_procedures=[
            SpecimenProcedure(
                procedure_type="Sectioning",
                specimen_id=subject_id,
                start_date=_SECTIONING_DATE,
                end_date=_SECTIONING_DATE,
                experimenters=_SECTIONING_EXPERIMENTERS,
                procedure_details=[_mapseq_first_batch(subject_id, cfg)],
                notes=f"MAPseq first batch: sections 1-{n_first} ({_MAPSEQ_THICKNESS_UM}um thick, partial slices)",
            ),
            SpecimenProcedure(
                procedure_type="Sectioning",
                specimen_id=subject_id,
                start_date=_SECTIONING_DATE,
                end_date=_SECTIONING_DATE,
                experimenters=_SECTIONING_EXPERIMENTERS,
                procedure_details=[_barseq_lc(subject_id, cfg)],
                notes=f"BARseq LC sections 1-{cfg['barseq_count']} ({_BARSEQ_THICKNESS_UM}um thick)",
            ),
            SpecimenProcedure(
                procedure_type="Sectioning",
                specimen_id=subject_id,
                start_date=_SECTIONING_DATE,
                end_date=_SECTIONING_DATE,
                experimenters=_SECTIONING_EXPERIMENTERS,
                procedure_details=[_mapseq_second_batch(subject_id, cfg)],
                notes=f"MAPseq second batch: sections {n_first + 1}-{n_first + n_second} ({_MAPSEQ_THICKNESS_UM}um thick, partial slices)",
            ),
            SpecimenProcedure(
                procedure_type="Sectioning",
                specimen_id=subject_id,
                start_date=_SECTIONING_DATE,
                end_date=_SECTIONING_DATE,
                experimenters=_SECTIONING_EXPERIMENTERS,
                procedure_details=[_spinal(subject_id, cfg)],
                notes="MAPseq spinal cord sections, size is approximate",
            ),
            *generate_mapseq_slide_chunks(subject_id),
        ],
    )


def _collect_specimen_ids(
    procedures: Procedures,
    *,
    type_predicate,
    pattern: re.Pattern,
) -> List[str]:
    ids: List[str] = []
    seen: set = set()
    for sp in procedures.specimen_procedures:
        for detail in sp.procedure_details:
            if not type_predicate(detail):
                continue
            for sec in detail.sections:
                sid = sec.output_specimen_id
                if sid in seen:
                    continue
                if not pattern.search(sid):
                    continue
                seen.add(sid)
                ids.append(sid)
    return ids


def _mapseq_specimen_ids(procedures: Procedures) -> List[str]:
    """Chunk-level MAPseq IDs (e.g. 780345_map001_001) — the brain-region pieces sent to CSHL.

    Filters strictly by `type(detail) is Sectioning` (not the PlanarSectioning
    subclass) so the upstream slice IDs (e.g. 780345_map001) are excluded.
    """
    return _collect_specimen_ids(
        procedures,
        type_predicate=lambda d: type(d) is Sectioning,
        pattern=_CHUNK_PATTERN,
    )


def _barseq_specimen_ids(procedures: Procedures) -> List[str]:
    """Section-level BARseq IDs (e.g. 780345_bar001) — the LC slides imaged in-house."""
    return _collect_specimen_ids(
        procedures,
        type_predicate=lambda d: isinstance(d, PlanarSectioning),
        pattern=_BAR_PATTERN,
    )


def build_mapseq_acquisition(
    subject_id: str,
    cfg: dict,
    procedures: Procedures,
) -> Acquisition:
    start = cfg["mapseq_start"]
    end = cfg["mapseq_end"]
    return Acquisition(
        subject_id=subject_id,
        specimen_id=_mapseq_specimen_ids(procedures),
        acquisition_start_time=start,
        acquisition_end_time=end,
        experimenters=cfg["mapseq_experimenters"],
        protocol_id=_MAPSEQ_PROTOCOL_ID,
        acquisition_type="BarcodeSequencing",
        notes=_augment_notes(_MAPSEQ_ACQUISITION_NOTE),
        data_streams=[
            ExternalDataStream(
                stream_start_time=start,
                stream_end_time=end,
                modalities=[Modality.MAPSEQ],
                notes=_MAPSEQ_STREAM_NOTE,
            )
        ],
    )


def build_barseq_acquisition(
    subject_id: str,
    cfg: dict,
    procedures: Procedures,
) -> Acquisition:
    start = cfg["barseq_start"]
    end = cfg["barseq_end"]
    return Acquisition(
        subject_id=subject_id,
        specimen_id=_barseq_specimen_ids(procedures),
        acquisition_start_time=start,
        acquisition_end_time=end,
        experimenters=cfg["barseq_experimenters"],
        protocol_id=_BARSEQ_PROTOCOL_ID,
        acquisition_type="BarcodeSequencing",
        notes=_augment_notes(_BARSEQ_ACQUISITION_NOTE),
        data_streams=[
            ExternalDataStream(
                stream_start_time=start,
                stream_end_time=end,
                modalities=[Modality.BARSEQ],
                notes=_BARSEQ_STREAM_NOTE,
            )
        ],
    )
