"""Provenance stamp shared across every generated JSON.

When this capsule is published as a Code Ocean release, set PROVENANCE_URL
to the release URL. _augment_notes appends a "Generated by: <url>" line to
the `notes` field of any model that includes it, so downstream readers can
trace each artifact back to the exact code that produced it.
"""

from typing import Optional

# e.g. "https://codeocean.allenneuraldynamics.org/capsule/<id>"
PROVENANCE_URL: Optional[str] = "https://codeocean.allenneuraldynamics.org/capsule/2979188"


def augment_notes(notes: str) -> str:
    """Append a "Generated by: <url>" line to a notes string if PROVENANCE_URL is set.

    Args:
        notes: Original notes string.

    Returns:
        Original `notes` unchanged if PROVENANCE_URL is None; otherwise
        `notes` with a blank line and `Generated by: <PROVENANCE_URL>` appended.
    """
    if PROVENANCE_URL:
        return f"{notes}\n\nGenerated by: {PROVENANCE_URL}"
    return notes
