"""Provenance stamp shared across every generated JSON.

When this capsule is published as a Code Ocean release, set PROVENANCE_URL
to the release URL. _augment_notes appends a "Generated by: <url>" line to
the `notes` field of any model that includes it, so downstream readers can
trace each artifact back to the exact code that produced it.
"""

from typing import Optional

# e.g. "https://codeocean.allenneuraldynamics.org/capsule/<id>"
PROVENANCE_URL: Optional[str] = None


def augment_notes(notes: str) -> str:
    """Append the provenance URL to a notes string if PROVENANCE_URL is set."""
    if PROVENANCE_URL:
        return f"{notes}\n\nGenerated by: {PROVENANCE_URL}"
    return notes
