"""Provenance stamp shared across every generated JSON.

When this capsule is published as a Code Ocean release, set PROVENANCE_URL
to the release URL. _augment_notes appends a "Generated by: <url>" line to
the `notes` field of any model that includes it, so downstream readers can
trace each artifact back to the exact code that produced it.
"""

from typing import Optional

# e.g. "https://codeocean.allenneuraldynamics.org/capsule/<id>"
PROVENANCE_URL: Optional[str] = "https://codeocean.allenneuraldynamics.org/capsule/2979188"


def augment_notes(notes: Optional[str]) -> Optional[str]:
    """Append a "Generated by: <url>" line if PROVENANCE_URL is set.

    Used for any free-form prose field that should carry the provenance
    stamp (notes on Procedures / Subject / Acquisition; data_summary on
    DataDescription, since DataDescription has no notes field).

    Args:
        notes: Existing field value. May be None or an empty string.

    Returns:
        - If PROVENANCE_URL is None: `notes` unchanged.
        - If `notes` is non-empty: `notes` with a blank line and
          "Generated by: <url>" appended.
        - If `notes` is None or empty: just "Generated by: <url>".
    """
    if not PROVENANCE_URL:
        return notes
    if notes:
        return f"{notes}\n\nGenerated by: {PROVENANCE_URL}"
    return f"Generated by: {PROVENANCE_URL}"
